[package]
name = "asciibrot"
version = "0.1.0"
authors = ["Tony Olagbaiye <frony0@gmail.com>"]

[dependencies]
lazy_static = "0.2.8"
ncurses = "5.86.0"
cached = "0.4.1"
rayon = "0.8.2"
libc = "0.2.30"
num = "0.1.40"

[[bin]]
name = "asciibrot"
test = false
doc = false
