[package]
name = "asciibrot"
version = "0.1.0"
authors = ["Tony Olagbaiye <frony0@gmail.com>"]

[dependencies]
ncurses = "5.86.0"
libc = "0.2.30"
num = "0.1.40"

[[bin]]
name = "asciibrot"
test = false
doc = false
